version: '3.1'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    command: [--auth]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: dbRa
    ports:
      - 27017:27017

