server:
  port: 8662

spring:
  application:
    name: gateway-service

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8661/eureka/

zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  ignored-services: '*'
  routes:
    api-consumers:
      path: /consumers/**
      serviceId : api-consumers
      stripPrefix : true
    api-companies:
      path: /companies/**
      serviceId: api-companies
      stripPrefix: true